/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GameApplication;

import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 * Menu is a JFrame GUI that is used in the Playing Screen for the player to:
 * 1) View rules again
 * 2) Forfeit the match
 * 3) Return back to the game.
 * The different buttons display the corresponding screens and the functionalities.
 * 
 * @author Daniel Kathiresan
 * @author Taylor Pringle
 * @author Prayag Shethia
 */
public class Menu extends javax.swing.JFrame {

    UnoGUI unoGUI;
    UnoPlayScreen unoPlayScreen;
    /**
     * Creates new form Menu
     */
    public Menu(UnoGUI unoGUI,UnoPlayScreen playScreen) {
        setUndecorated(true);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        initComponents();
        this.unoGUI = unoGUI;
        unoPlayScreen = playScreen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        rulesMenuButton = new javax.swing.JButton();
        forfeitMenuButton = new javax.swing.JButton();
        closeMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setText("MENU");

        rulesMenuButton.setBackground(new java.awt.Color(255, 255, 255));
        rulesMenuButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rulesMenuButton.setText("VIEW RULES");
        rulesMenuButton.setBorder(null);
        rulesMenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rulesMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesMenuButtonActionPerformed(evt);
            }
        });

        forfeitMenuButton.setBackground(new java.awt.Color(255, 255, 255));
        forfeitMenuButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        forfeitMenuButton.setText("FORFEIT GAME");
        forfeitMenuButton.setBorder(null);
        forfeitMenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forfeitMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forfeitMenuButtonActionPerformed(evt);
            }
        });

        closeMenuButton.setBackground(new java.awt.Color(255, 255, 255));
        closeMenuButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        closeMenuButton.setText("CLOSE MENU");
        closeMenuButton.setBorder(null);
        closeMenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closeMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(forfeitMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(rulesMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rulesMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forfeitMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rulesMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesMenuButtonActionPerformed
        this.setVisible(false);
        this.unoGUI.setVisible(true);
        this.unoGUI.displayRulesFromMenu();
    }//GEN-LAST:event_rulesMenuButtonActionPerformed

    private void forfeitMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forfeitMenuButtonActionPerformed
        int yesorno = JOptionPane.showConfirmDialog(null, "Do you wish to forfeit game?", "FORFEIT", JOptionPane.YES_NO_OPTION);
        if(yesorno == 0){
            Game.forfeit = true;
            Game.endGame();
            this.dispose();
            unoPlayScreen.dispose();
            this.unoGUI.setVisible(true);
            unoGUI.endGamePanelDisplay();
        }
    }//GEN-LAST:event_forfeitMenuButtonActionPerformed

    private void closeMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeMenuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeMenuButton;
    private javax.swing.JButton forfeitMenuButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JButton rulesMenuButton;
    // End of variables declaration//GEN-END:variables
}
