/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GameApplication;

import java.awt.Font;
import java.awt.Point;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import javax.swing.UIManager;
import javax.swing.text.html.HTMLDocument;

/**
 * UnoGUI is the main GUI frame having the different panels as layered panels.
 * The panels switch visibility when buttons are pressed.
 * UnoGUI runs the entire functionality and connection from the start till the end.
 * It also manages the playing screen and action listeners for various buttons.
 * 
 * @author prayagshethia
 * @author taylor
 * @author daniel
 */
public class UnoGUI extends javax.swing.JFrame {

   // PlayerRecords playerRecords = new PlayerRecords();
    ReadRules readRules = new ReadRules();
    UnoPlayScreen playingScreen = new UnoPlayScreen(this);
    GameApplication unoGame = new GameApplication();
    Toast toast = Turns.toast;
    
    /**
     * Creates new form UnoGUI
     */
    public UnoGUI() {
        initComponents();
        setupIcons();
        setupRules();
    }
    
    /**
     * The method is called initially to set up the label icons.
     */
    public void setupIcons(){
        SetIconLabel setIconLabel1 = new SetIconLabel("./Images/uno.png",unoLabel);
        setIconLabel1.setIcon();
        
        SetIconLabel setIconLabel2 = new SetIconLabel("./Images/uno.png",rulesLabel);
        setIconLabel2.setIcon();
        
        SetIconLabel setIconLabel3 = new SetIconLabel("./Images/uno.png",endGameLabel);
        setIconLabel3.setIcon();
        
        SetIconLabel setIconLabel4 = new SetIconLabel("./Images/uno.png",unoLabelAddPlayers);
        setIconLabel4.setIcon();
    }
    
    /**
     * The function sets up the rules by reading it and displaying it on the rules panel text area.
     */
    public void setupRules(){
        rulesTextPane.setText(readRules.readRules());
        Font font = new Font("Arial", Font.PLAIN, 14);
        String bodyRule = "body { font-family: " + font.getFamily() + "; " +
            "font-size: " + font.getSize() + "pt; }";
        ((HTMLDocument)rulesTextPane.getDocument()).getStyleSheet().addRule(bodyRule);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLayeredPane = new javax.swing.JLayeredPane();
        startScreenPanel = new javax.swing.JPanel();
        unoLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        rulesButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        rulesPanel = new javax.swing.JPanel();
        rulesLabel = new javax.swing.JLabel();
        letsPlayButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        rulesScrollPane = new javax.swing.JScrollPane();
        rulesTextPane = new javax.swing.JEditorPane();
        addPlayersPanel = new javax.swing.JPanel();
        player1Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        player1TextField = new javax.swing.JTextField();
        player2TextField = new javax.swing.JTextField();
        savePlayersButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        unoLabelAddPlayers = new javax.swing.JLabel();
        endGamePanel = new javax.swing.JPanel();
        endGameLabel = new javax.swing.JLabel();
        scoresSavedLabel = new javax.swing.JLabel();
        winnerLabel = new javax.swing.JLabel();
        winnerUsernameLabel = new javax.swing.JLabel();
        gameLogButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        gameLogPanel = new javax.swing.JPanel();
        gameLogCloseButton = new javax.swing.JButton();
        gameLogLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        gameLogTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainLayeredPane.setLayout(new java.awt.CardLayout());

        startScreenPanel.setBackground(new java.awt.Color(255, 86, 89));
        startScreenPanel.setName("startScreen"); // NOI18N

        unoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        startButton.setBackground(new java.awt.Color(255, 255, 255));
        startButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        startButton.setText("START GAME");
        startButton.setBorder(null);
        startButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startButton.setFocusable(false);
        startButton.setPreferredSize(new java.awt.Dimension(171, 47));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        rulesButton.setBackground(new java.awt.Color(255, 255, 255));
        rulesButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rulesButton.setText("VIEW RULES");
        rulesButton.setBorder(null);
        rulesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rulesButton.setFocusable(false);
        rulesButton.setMaximumSize(new java.awt.Dimension(171, 47));
        rulesButton.setMinimumSize(new java.awt.Dimension(171, 47));
        rulesButton.setPreferredSize(new java.awt.Dimension(171, 47));
        rulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesButtonActionPerformed(evt);
            }
        });

        quitButton.setBackground(new java.awt.Color(255, 255, 255));
        quitButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        quitButton.setText("QUIT");
        quitButton.setBorder(null);
        quitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitButton.setFocusable(false);
        quitButton.setMaximumSize(new java.awt.Dimension(171, 47));
        quitButton.setMinimumSize(new java.awt.Dimension(171, 47));
        quitButton.setPreferredSize(new java.awt.Dimension(171, 47));
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startScreenPanelLayout = new javax.swing.GroupLayout(startScreenPanel);
        startScreenPanel.setLayout(startScreenPanelLayout);
        startScreenPanelLayout.setHorizontalGroup(
            startScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startScreenPanelLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(unoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(startScreenPanelLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(startScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rulesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        startScreenPanelLayout.setVerticalGroup(
            startScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startScreenPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(unoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rulesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        unoLabel.getAccessibleContext().setAccessibleName("unoLogo");

        mainLayeredPane.add(startScreenPanel, "card2");
        startScreenPanel.getAccessibleContext().setAccessibleName("startScreen");

        rulesPanel.setBackground(new java.awt.Color(255, 86, 89));
        rulesPanel.setToolTipText("");
        rulesPanel.setName("rulesPanel"); // NOI18N

        letsPlayButton.setBackground(new java.awt.Color(255, 255, 255));
        letsPlayButton.setText("LET'S PLAY!");
        letsPlayButton.setBorder(null);
        letsPlayButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        letsPlayButton.setFocusable(false);
        letsPlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letsPlayButtonActionPerformed(evt);
            }
        });

        closeButton.setBackground(new java.awt.Color(255, 255, 255));
        closeButton.setText("CLOSE");
        closeButton.setBorder(null);
        closeButton.setBorderPainted(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.setFocusable(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        rulesScrollPane.setBorder(null);

        rulesTextPane.setBorder(null);
        rulesTextPane.setContentType("text/html"); // NOI18N
        rulesTextPane.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        rulesTextPane.setAutoscrolls(false);
        rulesTextPane.setMargin(new java.awt.Insets(0, 5, 5, 20));
        rulesScrollPane.setViewportView(rulesTextPane);

        javax.swing.GroupLayout rulesPanelLayout = new javax.swing.GroupLayout(rulesPanel);
        rulesPanel.setLayout(rulesPanelLayout);
        rulesPanelLayout.setHorizontalGroup(
            rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rulesPanelLayout.createSequentialGroup()
                .addGroup(rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rulesPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rulesPanelLayout.createSequentialGroup()
                                .addComponent(letsPlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rulesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rulesPanelLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(rulesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        rulesPanelLayout.setVerticalGroup(
            rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rulesPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(rulesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rulesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letsPlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        rulesLabel.getAccessibleContext().setAccessibleName("rulesLabel");
        letsPlayButton.getAccessibleContext().setAccessibleName("LETSPLAY");
        letsPlayButton.getAccessibleContext().setAccessibleDescription("");

        mainLayeredPane.add(rulesPanel, "card3");
        rulesPanel.getAccessibleContext().setAccessibleName("rulesPanel");

        addPlayersPanel.setBackground(new java.awt.Color(255, 86, 89));

        player1Label.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        player1Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        player1Label.setText("Player 1: ");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Player 2: ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        player1TextField.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        player1TextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        player1TextField.setMargin(new java.awt.Insets(0, 5, 0, 0));
        player1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1TextFieldActionPerformed(evt);
            }
        });

        player2TextField.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        player2TextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        player2TextField.setMargin(new java.awt.Insets(0, 5, 0, 0));

        savePlayersButton.setBackground(new java.awt.Color(255, 255, 255));
        savePlayersButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        savePlayersButton.setText("SAVE");
        savePlayersButton.setBorder(null);
        savePlayersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savePlayersButton.setFocusable(false);
        savePlayersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePlayersButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 255, 255));
        cancelButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelButton.setText("CANCEL");
        cancelButton.setBorder(null);
        cancelButton.setBorderPainted(false);
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.setFocusable(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        unoLabelAddPlayers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout addPlayersPanelLayout = new javax.swing.GroupLayout(addPlayersPanel);
        addPlayersPanel.setLayout(addPlayersPanelLayout);
        addPlayersPanelLayout.setHorizontalGroup(
            addPlayersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPlayersPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(addPlayersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPlayersPanelLayout.createSequentialGroup()
                        .addComponent(savePlayersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPlayersPanelLayout.createSequentialGroup()
                        .addGroup(addPlayersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(player1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(addPlayersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(player1TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(player2TextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPlayersPanelLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(unoLabelAddPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        addPlayersPanelLayout.setVerticalGroup(
            addPlayersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPlayersPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(unoLabelAddPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(addPlayersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(addPlayersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(addPlayersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savePlayersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        mainLayeredPane.add(addPlayersPanel, "card4");

        endGamePanel.setBackground(new java.awt.Color(255, 86, 89));
        endGamePanel.setName("EndGame"); // NOI18N

        endGameLabel.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        endGameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        scoresSavedLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        scoresSavedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoresSavedLabel.setText("Scores Saved Successfully");

        winnerLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        winnerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winnerLabel.setText("Winner: ");

        winnerUsernameLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        winnerUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        gameLogButton.setBackground(new java.awt.Color(255, 255, 255));
        gameLogButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gameLogButton.setText("GAME LOG");
        gameLogButton.setBorder(null);
        gameLogButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gameLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameLogButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        exitButton.setText("EXIT");
        exitButton.setBorder(null);
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout endGamePanelLayout = new javax.swing.GroupLayout(endGamePanel);
        endGamePanel.setLayout(endGamePanelLayout);
        endGamePanelLayout.setHorizontalGroup(
            endGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, endGamePanelLayout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addComponent(gameLogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(endGamePanelLayout.createSequentialGroup()
                .addGroup(endGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(endGamePanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(endGameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(endGamePanelLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(winnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(endGamePanelLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(scoresSavedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(endGamePanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(winnerUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        endGamePanelLayout.setVerticalGroup(
            endGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endGamePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(endGameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(winnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(winnerUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(scoresSavedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(endGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gameLogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        mainLayeredPane.add(endGamePanel, "card5");
        endGamePanel.getAccessibleContext().setAccessibleName("EndGame");

        gameLogPanel.setBackground(new java.awt.Color(255, 86, 89));

        gameLogCloseButton.setBackground(new java.awt.Color(255, 255, 255));
        gameLogCloseButton.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        gameLogCloseButton.setText("CLOSE");
        gameLogCloseButton.setBorder(null);
        gameLogCloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gameLogCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameLogCloseButtonActionPerformed(evt);
            }
        });

        gameLogLabel.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        gameLogLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameLogLabel.setText("Game Log");

        jScrollPane2.setBorder(null);

        gameLogTextArea.setEditable(false);
        gameLogTextArea.setColumns(20);
        gameLogTextArea.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        gameLogTextArea.setRows(5);
        gameLogTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jScrollPane2.setViewportView(gameLogTextArea);

        javax.swing.GroupLayout gameLogPanelLayout = new javax.swing.GroupLayout(gameLogPanel);
        gameLogPanel.setLayout(gameLogPanelLayout);
        gameLogPanelLayout.setHorizontalGroup(
            gameLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameLogPanelLayout.createSequentialGroup()
                .addGroup(gameLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameLogPanelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(gameLogCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameLogPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(gameLogLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameLogPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        gameLogPanelLayout.setVerticalGroup(
            gameLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameLogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameLogLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gameLogCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        mainLayeredPane.add(gameLogPanel, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainLayeredPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 595, Short.MAX_VALUE)
        );

        mainLayeredPane.getAccessibleContext().setAccessibleName("mainLayeredPane");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rulesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesButtonActionPerformed
        displayRulesPanel();
        rulesTextPane.setCaretPosition(0);
    }//GEN-LAST:event_rulesButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        displayPlayersPanel();
    }//GEN-LAST:event_startButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        int yesorno = JOptionPane.showConfirmDialog(null, "Are you sure you want to quit the game?", "QUIT GAME", JOptionPane.YES_NO_OPTION);
        if(yesorno == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_quitButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        if(playingScreen.isVisible()){
            rulesPanel.setVisible(false);
            addPlayersPanel.setVisible(false);
            endGamePanel.setVisible(false);
            gameLogPanel.setVisible(false);
            startScreenPanel.setVisible(false);
            playingScreen.setVisible(true);
        }
        else{
            rulesPanel.setVisible(false);
            addPlayersPanel.setVisible(false);
            endGamePanel.setVisible(false);
            gameLogPanel.setVisible(false);
            startScreenPanel.setVisible(true);
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void letsPlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letsPlayButtonActionPerformed
        if(playingScreen.isVisible()){
            rulesPanel.setVisible(false);
            addPlayersPanel.setVisible(false);
            endGamePanel.setVisible(false);
            gameLogPanel.setVisible(false);
            startScreenPanel.setVisible(false);
            playingScreen.setVisible(true);
        }
        else{
            displayPlayersPanel(); 
        }
    }//GEN-LAST:event_letsPlayButtonActionPerformed

    private void gameLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameLogButtonActionPerformed
        rulesPanel.setVisible(false);
        startScreenPanel.setVisible(false);
        endGamePanel.setVisible(false);
        addPlayersPanel.setVisible(false);
        unoGame.displayGameLogNew(gameLogTextArea);
        gameLogPanel.setVisible(true);
    }//GEN-LAST:event_gameLogButtonActionPerformed

    private void savePlayersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePlayersButtonActionPerformed
        String player1Name = player1TextField.getText().trim();
        String player2Name = player2TextField.getText().trim();
        
        if(player1Name.equalsIgnoreCase(player2Name)){
            JOptionPane.showMessageDialog(null, "<html>Player names cannot be the same.<br>Try again!</html>","Player Name Issue",JOptionPane.ERROR_MESSAGE);
        }
        else if(player1Name.isEmpty()|| player2Name.isEmpty()){
            JOptionPane.showMessageDialog(null, "<html>Player names cannot be the empty.<br>Try again!</html>","Player Name Issue",JOptionPane.ERROR_MESSAGE);
        }
        else{
            unoGame.savePlayerNames(player1TextField.getText(),player2TextField.getText());
            savePlayersButton.setVisible(false);
            initializeGame();
        }
    }//GEN-LAST:event_savePlayersButtonActionPerformed

    private void gameLogCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameLogCloseButtonActionPerformed
        rulesPanel.setVisible(false);
        startScreenPanel.setVisible(false);
        gameLogPanel.setVisible(false);
        addPlayersPanel.setVisible(false); 
        endGamePanel.setVisible(true);
    }//GEN-LAST:event_gameLogCloseButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Thanks for playing. Have a lovely day. :)","",JOptionPane.PLAIN_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        rulesPanel.setVisible(false);
        gameLogPanel.setVisible(false);
        addPlayersPanel.setVisible(false);
        endGamePanel.setVisible(false);
        startScreenPanel.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void player1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player1TextFieldActionPerformed
   
    public void displayPlayersPanel(){
        rulesPanel.setVisible(false);
        startScreenPanel.setVisible(false);
        endGamePanel.setVisible(false);
        gameLogPanel.setVisible(false);
        addPlayersPanel.setVisible(true);
    }
     
    public void displayRulesPanel(){
        startScreenPanel.setVisible(false);
        addPlayersPanel.setVisible(false);
        rulesPanel.setVisible(true);
        rulesTextPane.setCaretPosition(0);
    }
    
    public void displayRulesFromMenu(){
        startScreenPanel.setVisible(false);
        addPlayersPanel.setVisible(false);
        letsPlayButton.setVisible(false);
        rulesPanel.setVisible(true);
        rulesTextPane.setCaretPosition(0);
    }
    
    public void endGamePanelDisplay(){
        rulesPanel.setVisible(false);
        addPlayersPanel.setVisible(false);
        startScreenPanel.setVisible(false);
        gameLogPanel.setVisible(false);
        endGamePanel.setVisible(true);
        winnerUsernameLabel.setText(Game.winner.getUserName());
        GameApplication.uno.writePlayerRecordDB(Game.player1, Game.player2);
    }
    
    /**
     * Manages the initial setup of the game playing screen by setting the buttons, visibilities and pop ups.
     */
    public void initializeGame(){
        unoGame.game.startGame();
        Hand.playingScreen = playingScreen;
        playingScreen.setButtons();
        playingScreen.setPlayerNames();
        playingScreen.setVisible(true);
        toast.makeToast("<html>"+unoGame.game.PLAYER1NAME+" will be starting first!</html>", 2);
        this.setVisible(false);
        rulesPanel.setVisible(false);
        startScreenPanel.setVisible(false);
        endGamePanel.setVisible(false);
        addPlayersPanel.setVisible(false);
        gameLogPanel.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(
                UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPlayersPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel endGameLabel;
    private javax.swing.JPanel endGamePanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton gameLogButton;
    private javax.swing.JButton gameLogCloseButton;
    private javax.swing.JLabel gameLogLabel;
    private javax.swing.JPanel gameLogPanel;
    private javax.swing.JTextArea gameLogTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton letsPlayButton;
    private javax.swing.JLayeredPane mainLayeredPane;
    private javax.swing.JLabel player1Label;
    private javax.swing.JTextField player1TextField;
    private javax.swing.JTextField player2TextField;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton rulesButton;
    private javax.swing.JLabel rulesLabel;
    private javax.swing.JPanel rulesPanel;
    private javax.swing.JScrollPane rulesScrollPane;
    private javax.swing.JEditorPane rulesTextPane;
    private javax.swing.JButton savePlayersButton;
    private javax.swing.JLabel scoresSavedLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel startScreenPanel;
    private javax.swing.JLabel unoLabel;
    private javax.swing.JLabel unoLabelAddPlayers;
    private javax.swing.JLabel winnerLabel;
    private javax.swing.JLabel winnerUsernameLabel;
    // End of variables declaration//GEN-END:variables
}
