/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GameApplication;

import static GameApplication.Turns.toast;
import javax.swing.JOptionPane;

/**
 * Wild Colour frame is used to ask the user to select the colour for wild card that they want to change.
 * There are 4 buttons for the 4 colours, and each action listener sets the corresponding colour and the image reference.
 * 
 * @author Daniel Kathiresan
 * @author Taylor Pringle
 * @author Prayag Shethia
 */
public class WildColour extends javax.swing.JFrame {

    UnoPlayScreen playingScreen;
    public static char colour;
    WildCard wildCard;
    
    /**
     * Creates new form WildColour
     */
    public WildColour(UnoPlayScreen playingScreen, WildCard wildCard) {
        initComponents();
        this.playingScreen = playingScreen;
        this.wildCard = wildCard;
    }
    
    public void setColour(char colour){
        this.colour = colour;
    }
    
    /**
     * ManageWildColour is used to switch back to the playingScreen 
     * and calls the implement card function in the wild card while shutting down the wild colour frame.
     */
    public void manageWildColour(){
        playingScreen.setEnabled(true);
        this.dispose();
        if(Game.currentPlayer.hand.hand.size() == 1){
            JOptionPane.showMessageDialog(null, "It's the last card!\n------**UNO**-----","LAST CARD",JOptionPane.INFORMATION_MESSAGE);
        }
        wildCard.implementCard();
        Turns.showToast(wildCard.type);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        redButton = new javax.swing.JButton();
        blueButton = new javax.swing.JButton();
        greenButton = new javax.swing.JButton();
        yellowButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wild Card");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select a colour");

        redButton.setBackground(new java.awt.Color(255, 255, 255));
        redButton.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        redButton.setText("RED");
        redButton.setBorder(null);
        redButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        redButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redButtonActionPerformed(evt);
            }
        });

        blueButton.setBackground(new java.awt.Color(255, 255, 255));
        blueButton.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        blueButton.setText("BLUE");
        blueButton.setBorder(null);
        blueButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueButtonActionPerformed(evt);
            }
        });

        greenButton.setBackground(new java.awt.Color(255, 255, 255));
        greenButton.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        greenButton.setText("GREEN");
        greenButton.setBorder(null);
        greenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        greenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenButtonActionPerformed(evt);
            }
        });

        yellowButton.setBackground(new java.awt.Color(255, 255, 255));
        yellowButton.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        yellowButton.setText("YELLOW");
        yellowButton.setAutoscrolls(true);
        yellowButton.setBorder(null);
        yellowButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yellowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(redButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(blueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(greenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yellowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
        setColour('R');
        if(wildCard.plusFour){
            Game.playedCard.setImageRef("./resources/uno-cards/wild_red_plus_four.png");
        }else{
            Game.playedCard.setImageRef("./resources/uno-cards/wild_red.png");
        }   
        manageWildColour();
        //call card
    }//GEN-LAST:event_redButtonActionPerformed

    private void blueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueButtonActionPerformed
        setColour('B');
        if(wildCard.plusFour){
            Game.playedCard.setImageRef("./resources/uno-cards/wild_blue_plus_four.png");
        }else{
            Game.playedCard.setImageRef("./resources/uno-cards/wild_blue.png");
        }
        manageWildColour();
    }//GEN-LAST:event_blueButtonActionPerformed

    private void greenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenButtonActionPerformed
        setColour('G');
        if(wildCard.plusFour){
            Game.playedCard.setImageRef("./resources/uno-cards/wild_green_plus_four.png");
        }else{
            Game.playedCard.setImageRef("./resources/uno-cards/wild_green.png");
        }
        manageWildColour();
    }//GEN-LAST:event_greenButtonActionPerformed

    private void yellowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowButtonActionPerformed
        setColour('Y');
        if(wildCard.plusFour){
            Game.playedCard.setImageRef("./resources/uno-cards/wild_yellow_plus_four.png");
        }else{
            Game.playedCard.setImageRef("./resources/uno-cards/wild_yellow.png");
        }
        manageWildColour();
    }//GEN-LAST:event_yellowButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blueButton;
    private javax.swing.JButton greenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton redButton;
    private javax.swing.JButton yellowButton;
    // End of variables declaration//GEN-END:variables
}
